### ISSUE TITLE
multiup.org

### ISSUE THREAD

**Issue by ghajini** [LiCybora/NanoDefenderFirefox#156] opened 2019-10-29 07:18 UTC
@LiCybora 
@jspenguin2017

### Test link (required):
`https://multiup.org/en/mirror/0e2b8dd1ac5011a04ca7769a4b27be03/ExtraMovies.wiki_FLM19S02E01.mkv`

### Screenshot of the web page (including address bar and extension icons) (required):
there is nothing to show

### Screenshot of the console (press `F12` to bring up the console) (required):

https://user-images.githubusercontent.com/20338483/67745582-9ec8e280-fa4a-11e9-8290-d0c80013a263.png

https://user-images.githubusercontent.com/20338483/67745583-9f617900-fa4a-11e9-8457-c522caaa460b.png

### Explain what was not right (optional if obvious):
i am not able to download from file from this site from file servers....ubo strict blocking dialogue comes for multinews,me and never proceeds

### Environment (Required):

- Operating System and Version: win 10
- Browser and Version: firefox 70.0
- Adblocker and Version: ublock origin and nano defender firefox with all default settings

#### Your filter lists (Required):

 the default settings

**Comment by jspenguin2017** [comment] 2019-10-31 02:33
Duplicate of https://github.com/NanoMeow/QuickReports/issues/2096

**Closed** 2019-11-03 03:45 UTC
Labels: duplicate

**Comment by ghajini** [comment] 2019-11-23 17:50
This is still not fixed in upstream, perhaps you can fix it here@LiCybora

**Comment by jspenguin2017** [comment] 2019-11-23 18:10
I haven't got time to look into it, feel free to send a PR.
