### ISSUE TITLE
Extra installation  steps" for Adblock Warning Removal List

### ISSUE THREAD

**Issue by mutantsushi** [LiCybora/NanoDefenderFirefox#189] opened 2020-10-21 01:43 UTC
First, 
Thanks for taking the extra steps to 100% break with these scammers so users can have peace of mind.
I am slightly confused by the given steps to "activate" NanoDefender with uBO:
"Extra installation steps for uBlock Origin
Step 1. Subscribe to Adblock Warning Removal List."

After I opened the AWRL link and click "Subscribe", and then return to the same link afresh, the Subscribe button is clickable.
This doesn't happen on the filter subscriptions (Nano Defender Integration/Nano filters) where after I hit Subscribe once
if I return to same link there is no Subscribe button because uBO already has integrated them (showing in filter list).
OK, AWRL isn't a filter subscription so it won't show up there, but the fact the Subscribe button keeps appearing makes it
seem like nothing happened as the extension seems to think I am not Subscribed, and the actual situation isn't clear.

Anyways, I'm not sure of fundamental Firefox limits on extension capabilities, if these extra set-up steps will always be needed
or if extension can eventually be updated to "just work" with uBO "out of the box" without adding special filters/etc like these,
but for the time being I'm worried it isn't fully configured correctly... Is this working as intended, or can I do something to fix it?

**Comment by hakimzulkufli** [comment] 2020-10-21 01:48
My guess is that uBlock Origin itself prevents you from using that specific list. I've looked around and it seems that gorhill doesn't want anyone to use that list since it is outdated and have compatibility issues with many websites.

**Comment by LiCybora** [comment] 2020-10-21 12:19
Since uBO 1.30.0, AWRL is [bad list](https://github.com/uBlockOrigin/uAssets/blob/master/filters/badlists.txt) due to issues with uBlock Origin.

Nano Defender can still works even without filter list, just this is not an expected behavior so we ask users to add AWRL. If you can't add, then just leave it without AWRL. I will also update instruction soon.

Issue is related to #185, so I will close it and move discussion to there.

**Closed by LiCybora** 2020-10-21 12:19 UTC
