### ISSUE TITLE
As.com

### ISSUE THREAD

**Issue by JoseHidalgo** [LiCybora/NanoDefenderFirefox#154] opened 2019-09-26 12:51 UTC
Just go to www.as.com , and you'll see the yellow pop-up at the bottom of the page : "You are seeing this message because ad or script blocking software is interfering with this page.
Disable any ad or script blocking software, then reload this page."

I have already reported several issues here. Always with the same browser (FF) and extensions (µBlock Origin, Nano Defender, Privacy Possum...). Sorry but I don't want to be forced to screen cap every time, disable extensions, enable them afterwards, etc..

Thanks for your understanding !

PS : I had the same issue today with www.okdiario.com . Probably because both sites are managed by the same company, which implemented some anti-block software today (I read them every day : yesterday everything was fine, and today both sites have the same pop-up).

**Comment by LiCybora** [comment] 2019-09-29 07:46
I cannot reproduce.
![image](https://user-images.githubusercontent.com/40160522/65828685-14b51f00-e2d0-11e9-9134-72b9f1b6e93c.png)

Can you fill in the template when reporting issues?

**Comment by JoseHidalgo** [comment] 2019-09-29 18:49
FYI the problem remained for 3 days, then today it spontaneously disappeared.
Could it be linked to an auto-update to the block-lists ? Just wondering.

**Comment by LiCybora** [comment] 2019-09-30 11:48
> Could it be linked to an auto-update to the block-lists ? Just wondering.

Probable. Anyway, closing as fixed.

**Closed by LiCybora** 2019-09-30 11:48 UTC
Labels: cannot reproduce
