### ISSUE TITLE
adf.ly

### ISSUE THREAD

**Issue by bugreporter6** [LiCybora/NanoDefenderFirefox#152] opened 2019-09-07 23:04 UTC
https://adf.ly/1UmOZS
<img width="960" alt="Przechwytywanie2" src="https://user-images.githubusercontent.com/55036180/64480984-b4045c00-d1d3-11e9-81e1-edcb38514338.PNG">
<img width="379" alt="Przechwytywanie" src="https://user-images.githubusercontent.com/55036180/64480990-bc5c9700-d1d3-11e9-8e63-d0b203cb4ceb.PNG">
It doesn't redirect to the destination page (http://ww25.new.rapeit.net/?z).
Wrong URLs: https://www1.ecleneue.com/pushredirect/?network=2&site=adfly&ppi=10178589&pci=4252004433&t=1567896670&dest=http%3A%2F%2Fnew.rapeit.net%2F
http://larati.net/ad/locked?rndad=2a02a314c53ffd0050ff80de9f57bb69-1567787641&url=1UmOZS&t=s&subid=10178589&h=1
http://larati.net/ad/locked?rndad=2a02a314c53ffd00138d719b19351cc-1567896625&url=1UmOZS&t=s&subid=10178589&h=1
Could you please fix it?

**Comment by LiCybora** [comment] 2019-09-08 12:58
I commented in NanoMeow/QuickReports#1789 as well, but that OP claims another destination page which confused me.

From my testing, it can redirect to destination page most of the time, but your problem is still reproducible sometimes. I guess there is some racing condition and I will try my best to stabilize it.

**Comment by krystian3w** [comment] 2019-09-08 17:59
https://github.com/NanoAdblocker/NanoFilters/issues/370 - if you try fix bait with webpush - AdGuard copy direct links form url: 

https://github.com/AdguardTeam/AdguardFilters/blob/27c04b9877bb32ffe2357033fe4242c5f0f6ec1b/AnnoyancesFilter/sections/tweaks.txt#L130

**Comment by ghajini** [comment] 2019-09-22 17:58
Hello @LiCybora, I don't know why many are not able to reproduce(whether at uassets,upstream jspenguin2017 repo,
https://github.com/NanoAdblocker/NanoFilters/issues/370)  but I can reproduce on opera browser/firefox desktop/firefox android......

Here's another site

`https://ww1.ouo.today/?oID=41450&cr=aHR0cDovL2pldGxlZWNoLm5ldC9yZWRpci5waHA/aWQ9aTNFX243M3JVeEpIa3RTMkxqbWFtaHIxQW8xNmFyYkNQcDhfSC1vXzR5N05FNmZMVzN4QndR`

**Comment by krystian3w** [comment] 2019-09-22 18:04
ND block push? I see with disabled CSP.

**Comment by ghajini** [comment] 2019-09-22 18:14
@krystian3w, I already tried disabling CSP in firefox, not work.....

@LiCybora I can provide any debug info you want?

**Comment by ghajini** [comment] 2019-09-23 10:36
Providing STR if you are IP-locked to above link(clear cookie+data before )

STR=

1.visit jetleech.net

Enter any site you want to leech
eg
https://www93.zippyshare.com/v/pMq3pyjk/file.html

Click download and follow subsequent steps, you will get above link shortener

Then you are stuck at ouo.today

**Comment by ghajini** [comment] 2019-09-23 13:55
Simple fix provided by @ghost for ouo.today
// ==UserScript==
// @name         ouo today
// @match        *://ww1.ouo.today/*
// @run-at       document-start
// @grant        none
// ==/UserScript==
(()=>location.replace(atob(new URLSearchParams(location.search).get("cr"))))()

**Comment by grant** [comment] 2019-09-23 14:32
Please don't mention me. Use \`\`\`.

```js
// ==UserScript==
// @name ouo today
// @match ://ww.ouo.today/*
// @run-at document-start
// @grant none
// ==/UserScript==
(()=>location.replace(atob(new URLSearchParams(location.search).get("cr"))))()
```

Unsubscribing.

**Comment by krystian3w** [comment] 2019-09-23 15:15
You Country block change first name...?

**Comment by ghajini** [comment] 2019-09-23 15:37
Offtopic 
@krystian3w your English ,I don't understand. ....

**Comment by krystian3w** [comment] 2019-09-23 15:44
fixed, I eaten "r".

**Comment by RedRocketCat** [comment] 2019-11-26 05:08
ulysses s. @grant was an american soldier and politician who served as the 18th president of the united states from 1869 to 1877. before his presidency, @grant led the union army in winning the american civil war.

**Comment by ghajini** [comment] 2020-03-10 16:09
Fix landed here 
https://github.com/NanoAdblocker/NanoFilters/issues/370
Waiting to be fixed in nano defender firefox/firefox android

**Comment by LiCybora** [comment] 2020-03-11 15:54
15.0.0.194 is up now. Closing as fixed. Feel free to post if there is also issue for the site.

**Closed by LiCybora** 2020-03-11 15:54 UTC
Labels: Fixed, WIP
