### ISSUE TITLE
[Anti-adblock] strims.world

### ISSUE THREAD

**Issue by Majkovsky** [LiCybora/NanoDefenderFirefox#160] opened 2019-12-22 10:06 UTC
http://strims.world/SkokiKwalifikacje.php?source=1

**"BRAK PLAYERA? WYŁĄCZ ADBLOCKA!"**

Nano Defender **15.0.0.170**
Mozilla Firefox **71.0**

**Comment by LiCybora** [comment] 2019-12-22 13:34
Can you fill in the template with screenshot and step to reproduce?

I cannot read those language and don't know which button to click. I just see list of links but do not see those wordings.

**Comment by LiCybora** [comment] 2020-01-28 16:54
Closing due to incomplete report. May reopen once required information is filled.

**Closed by LiCybora** 2020-01-28 16:54 UTC
